# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(
    r"C:\Users\benzo\PycharmProjects\NewUIExtended\Scripts\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def on_hover(event, change):
    event.widget.configure(image=change)


def on_leave(event, change):
    event.widget.configure(image=change)


def show_main_frame(main_frame, show_frame):
    main_canvas = Canvas(
        main_frame,
        bg="#FFFFFF",
        height=886,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    main_canvas.grid(row=0, column=0, sticky=NSEW)

    main_canvas.image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = main_canvas.create_image(
        720.0,
        512.0-70,
        image=main_canvas.image_image_1
    )

    main_canvas.image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = main_canvas.create_image(
        1089.0,
        581.0-138,
        image=main_canvas.image_image_2
    )

    main_canvas.create_text(
        88.0,
        385.0-138,
        anchor="nw",
        text="Welcome to Pythia\nEnhance Your Skills\n \n",
        fill="#000000",
        font=("InknutAntiqua Regular", 24 * -1)
    )

    main_canvas.create_text(
        88.0,
        547.0-138,
        anchor="nw",
        text="Pythia is designed to help students improve their skills through\n"
             "personalized testing. Each test evaluates your level and abilities,\n"
             "providing detailed progress statistics. Pythia then creates customized\n"
             "tests to target your needs, ensuring efficient skill enhancement. \n"
             "Join us and start improving your skills with Pythia!",
        fill="#000000",
        font=("Inter", 18 * -1)
    )

    # button_5.bind("<Enter>", lambda e: on_hover(e, button_image_5_hover))
    # button_5.bind("<Leave>", lambda e: on_hover(e, button_image_5))
