# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(
    r"frame2")


entry_1: Entry
entry_2: Entry
entry_3: Entry
entry_4: Entry
entry_5: Entry


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def insert_details_to_my_profile(name, grade, email, gender, dob):
    entry_1.insert(0, name)
    entry_1.configure(state='readonly', readonlybackground='#C9E2EE')
    entry_2.insert(0, grade)
    entry_2.configure(state='readonly', readonlybackground='#C9E2EE')
    entry_3.insert(0, email)
    entry_3.configure(state='readonly', readonlybackground='#C9E2EE')
    entry_4.insert(0, gender)
    entry_4.configure(state='readonly', readonlybackground='#C9E2EE')
    entry_5.insert(0, dob)
    entry_5.configure(state='readonly', readonlybackground='#C9E2EE')


# window = Tk()
#
# window.geometry("1440x886")
# window.configure(bg="#FFFFFF")

def show_my_profile_frame(main_frame, show_frame):
    global entry_1, entry_2, entry_3, entry_4, entry_5
    profile_canvas = Canvas(
        main_frame,
        bg="#FFFFFF",
        height=886,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    profile_canvas.grid(row=0, column=0, sticky=NSEW)

    profile_canvas.image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = profile_canvas.create_image(
        720.0,
        443.0,
        image=profile_canvas.image_image_1
    )

    profile_canvas.image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = profile_canvas.create_image(
        720.0,
        442.0,
        image=profile_canvas.image_image_2
    )

    profile_canvas.create_text(
        361.0,
        616.0,
        anchor="nw",
        text="Name",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = profile_canvas.create_image(
        397.0,
        458.0,
        image=profile_canvas.image_image_3
    )

    profile_canvas.entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = profile_canvas.create_image(
        996.0,
        210.5,
        image=profile_canvas.entry_image_1
    )
    entry_1 = Entry(
        main_frame,
        bd=0,
        bg="#C9E2EE",
        fg="#000716",
        highlightthickness=0,
        font=("Intern", 18)
    )
    entry_1.place(
        x=746.0,
        y=191.0,
        width=500.0,
        height=41.0
    )

    profile_canvas.entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_2 = profile_canvas.create_image(
        996.0,
        606.5,
        image=profile_canvas.entry_image_2
    )
    entry_2 = Entry(
        main_frame,
        bd=0,
        bg="#C9E2EE",
        fg="#000716",
        highlightthickness=0,
        font=("Intern", 18)
    )
    entry_2.place(
        x=746.0,
        y=587.0,
        width=500.0,
        height=41.0
    )

    profile_canvas.entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_3 = profile_canvas.create_image(
        996.0,
        507.5,
        image=profile_canvas.entry_image_3
    )
    entry_3 = Entry(
        main_frame,
        bd=0,
        bg="#C9E2EE",
        fg="#000716",
        highlightthickness=0,
        font=("Intern", 18)
    )
    entry_3.place(
        x=746.0,
        y=488.0,
        width=500.0,
        height=41.0
    )

    profile_canvas.entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_4 = profile_canvas.create_image(
        996.0,
        408.5,
        image=profile_canvas.entry_image_4
    )
    entry_4 = Entry(
        main_frame,
        bd=0,
        bg="#C9E2EE",
        fg="#000716",
        highlightthickness=0,
        font=("Intern", 18)
    )
    entry_4.place(
        x=746.0,
        y=389.0,
        width=500.0,
        height=41.0
    )

    profile_canvas.entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_5 = profile_canvas.create_image(
        996.0,
        309.5,
        image=profile_canvas.entry_image_5
    )
    entry_5 = Entry(
        main_frame,
        bd=0,
        bg="#C9E2EE",
        fg="#000716",
        highlightthickness=0,
        font=("Intern", 18)
    )
    entry_5.place(
        x=746.0,
        y=290.0,
        width=500.0,
        height=41.0
    )

    profile_canvas.create_text(
        942.0,
        154.0,
        anchor="nw",
        text="Full name",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.create_text(
        961.0,
        256.0,
        anchor="nw",
        text="DOB",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.create_text(
        965.0,
        355.0,
        anchor="nw",
        text="Gender",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.create_text(
        970.0,
        454.0,
        anchor="nw",
        text="Email\n",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.create_text(
        961.0,
        553.0,
        anchor="nw",
        text="Grade\n",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    profile_canvas.button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        main_frame,
        image=profile_canvas.button_image_1,
        borderwidth=0,
        highlightthickness=0,
        activebackground="#7DABB2",
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=905.0,
        y=681.0,
        width=198.0,
        height=51.0
    )

    profile_canvas.create_text(
        195.0,
        201.0,
        anchor="nw",
        text="My profile",
        fill="#000000",
        font=("Inter", 32 * -1)
    )

# window.resizable(False, False)
# window.mainloop()
