# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(
    r"C:\Users\benzo\PycharmProjects\TryNewUI\Scripts\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x886")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=886,
    width=1440,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    443.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    720.0,
    442.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    408.5,
    487.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=198.0,
    y=468.0,
    width=421.0,
    height=37.0
)

canvas.create_text(
    195.0,
    201.0,
    anchor="nw",
    text="Sign up",
    fill="#000000",
    font=("Inter", 34 * -1)
)

canvas.create_text(
    828.0,
    542.0,
    anchor="nw",
    text="Create password",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    195.0,
    542.0,
    anchor="nw",
    text="Enter email",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    823.0,
    426.0,
    anchor="nw",
    text="DOB",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    195.0,
    426.0,
    anchor="nw",
    text="Enter your grade",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    823.0,
    310.0,
    anchor="nw",
    text="Gender",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    195.0,
    310.0,
    anchor="nw",
    text="Enter full name",
    fill="#000000",
    font=("Inter", 24 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_2 = canvas.create_image(
    408.5,
    377.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=198.0,
    y=358.0,
    width=421.0,
    height=37.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_3 = canvas.create_image(
    1034.5,
    377.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=824.0,
    y=358.0,
    width=421.0,
    height=37.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_4 = canvas.create_image(
    408.5,
    611.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=198.0,
    y=592.0,
    width=421.0,
    height=37.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_5 = canvas.create_image(
    1034.5,
    487.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=824.0,
    y=468.0,
    width=421.0,
    height=37.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_6 = canvas.create_image(
    1034.5,
    611.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=824.0,
    y=592.0,
    width=421.0,
    height=37.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    activebackground="#96C1C9",
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=637.0,
    y=678.0,
    width=176.0,
    height=52.0
)
window.resizable(False, False)
window.mainloop()
